apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qxmm7gekp-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qxmm7gekp-dotnet-basic-gitops